class_name GameState
extends RefCounted
## Round accounting (build 010, end rules revised in build 012).
## A round has `total_humans` (20) humans: some placed at start, the rest
## generated by the camp.
## Build 012 end rules, checked after every event in this order:
##   1. WIN the moment rescued >= target (no need to resolve all 20).
##   2. LOSE early once the target is out of reach:
##      max_possible_saves() = total - dead - possessed_destroyed < target.
##      Humans still to arrive, silly humans in the field AND living possessed
##      humans (they can still be thrown into the safe zone) all count as savable.
##   3. Fallback (pre-012 rule): every human generated and resolved
##      (rescued + possessed + dead == total) with rescued < target -> lose.
##   Plus the rancher dying (trigger_lose(.., "rancher")).

signal rescued_changed(rescued: int, total: int)
signal dead_changed(dead: int)
signal possessed_changed(possessed: int)
signal counts_changed
signal player_health_changed(health: int, maximum: int)
signal won
signal lost(reason: String)

var rescued_humans: int = 0
var dead_humans: int = 0
var possessed_humans: int = 0
## Build 012: sheep exploded this round (+50 each).
var sheep_killed: int = 0
## Build 012: possessed humans destroyed this round (+50 each, counted like a
## monster kill). They stay counted in possessed_humans (resolved as lost).
var possessed_destroyed: int = 0
## Build 013: Karens destroyed (subset of possessed_destroyed, +100 each).
var karens_destroyed: int = 0
## Build 017: human spawn rolls that arrived as Cantifa instead (not saveable).
var cantifa_slots: int = 0
## Humans in this round (initial + camp). Build 010: 20.
var total_humans: int = 0
## Humans generated so far this round (initial placement + camp spawns).
var spawned_humans: int = 0
## Saves needed to clear the level.
var target_rescued: int = 1
var level: int = 1

var player_health: int = 5
var player_max_health: int = 5

var sheep_remaining: int = 0

var is_won: bool = false
var is_lost: bool = false
## "" while playing; "target" / "impossible" / "short" / "rancher" once over.
var end_kind: String = ""
## Win/lose only after level_controller finishes placement + registration.
var setup_complete: bool = false


func reset() -> void:
	rescued_humans = 0
	dead_humans = 0
	possessed_humans = 0
	sheep_killed = 0
	possessed_destroyed = 0
	karens_destroyed = 0
	cantifa_slots = 0
	total_humans = 0
	spawned_humans = 0
	target_rescued = 1
	player_health = 5
	player_max_health = 5
	sheep_remaining = 0
	is_won = false
	is_lost = false
	end_kind = ""
	setup_complete = false


func resolved_humans() -> int:
	return rescued_humans + possessed_humans + dead_humans


## Silly humans generated and still unresolved (in the field).
func living_silly() -> int:
	return maxi(spawned_humans - resolved_humans() - cantifa_slots, 0)


func living_uncounted() -> int:
	return living_silly()


## Humans the camp has not generated yet.
func humans_left_to_arrive() -> int:
	return maxi(total_humans - spawned_humans, 0)


## Build 012: best case saves still reachable this round.
func max_possible_saves() -> int:
	return maxi(total_humans - dead_humans - possessed_destroyed - cantifa_slots, 0)


## Build 017: a camp arrival was a Cantifa instead of a human. Counts as
## generated (the round still ends) but not as someone who can be saved.
func note_cantifa_slot() -> bool:
	if spawned_humans >= total_humans:
		return false
	spawned_humans += 1
	cantifa_slots += 1
	counts_changed.emit()
	_check_end()
	return true


## Build 017: one of the humans already placed at round start was a Cantifa.
## spawned_humans already includes them; this only marks the slot unsavable.
func convert_initial_to_cantifa() -> void:
	cantifa_slots += 1
	counts_changed.emit()
	_check_end()


## Possessed humans still walking around (savable by throwing them in the zone).
func living_possessed() -> int:
	return maxi(possessed_humans - possessed_destroyed, 0)


func all_spawned() -> bool:
	return spawned_humans >= total_humans


func mark_setup_complete() -> void:
	setup_complete = true


## Start a round: `total` humans overall, `initial` already on the map.
func begin_round(total: int, initial: int, target: int, level_number: int) -> void:
	total_humans = maxi(total, 0)
	spawned_humans = clampi(initial, 0, total_humans)
	cantifa_slots = 0
	target_rescued = target
	level = level_number
	rescued_humans = 0
	dead_humans = 0
	possessed_humans = 0
	sheep_killed = 0
	possessed_destroyed = 0
	karens_destroyed = 0
	cantifa_slots = 0
	rescued_changed.emit(rescued_humans, total_humans)
	dead_changed.emit(dead_humans)
	possessed_changed.emit(possessed_humans)
	counts_changed.emit()


## Legacy (pre-010): a round of exactly `count` humans, all present at start.
func register_humans(count: int) -> void:
	begin_round(count, count, mini(1, count), level)


## Camp generated one more human. Returns false once the round total is reached.
func note_human_spawned() -> bool:
	if spawned_humans >= total_humans:
		return false
	spawned_humans += 1
	counts_changed.emit()
	return true


func register_player(health: int, maximum: int) -> void:
	player_health = health
	player_max_health = maximum
	player_health_changed.emit(player_health, player_max_health)


func add_rescue() -> void:
	if not setup_complete or is_won or is_lost:
		return
	rescued_humans += 1
	rescued_changed.emit(rescued_humans, total_humans)
	counts_changed.emit()
	_check_end()


func add_human_death() -> void:
	if not setup_complete or is_won or is_lost:
		return
	dead_humans += 1
	dead_changed.emit(dead_humans)
	counts_changed.emit()
	_check_end()


func add_possession() -> void:
	if not setup_complete or is_won or is_lost:
		return
	possessed_humans += 1
	possessed_changed.emit(possessed_humans)
	counts_changed.emit()
	_check_end()


## Throw a possessed human into the safe zone: rescue credit, no death.
## Net: possessed--, rescued++ (resolved as rescue; do not double-count total).
func add_possession_save() -> void:
	if not setup_complete or is_won or is_lost:
		return
	possessed_humans = maxi(0, possessed_humans - 1)
	rescued_humans += 1
	possessed_changed.emit(possessed_humans)
	rescued_changed.emit(rescued_humans, total_humans)
	counts_changed.emit()
	_check_end()


## Build 012: a sheep exploded (whip / thrown sheep / thrown possessed human).
func add_sheep_kill() -> bool:
	if not setup_complete or is_won or is_lost:
		return false
	sheep_killed += 1
	counts_changed.emit()
	return true


## Build 012: a possessed human was destroyed (it was already counted as
## possessed; this only matters for the impossible-target check and score).
func add_possessed_destroyed() -> bool:
	if not setup_complete or is_won or is_lost:
		return false
	possessed_destroyed += 1
	counts_changed.emit()
	_check_end()
	return true


## Build 013: a Karen was destroyed. Counts exactly like a destroyed possessed
## human for the out-of-reach check.
func add_karen_destroyed() -> bool:
	if not setup_complete or is_won or is_lost:
		return false
	karens_destroyed += 1
	return add_possessed_destroyed()


func set_player_health(health: int) -> void:
	player_health = health
	player_health_changed.emit(player_health, player_max_health)
	if player_health <= 0:
		trigger_lose("The rancher is down.", "rancher")


func trigger_win() -> void:
	if not setup_complete or is_won or is_lost:
		return
	is_won = true
	end_kind = "target"
	won.emit()


func trigger_lose(reason: String, kind: String = "short") -> void:
	if not setup_complete or is_won or is_lost:
		return
	is_lost = true
	end_kind = kind
	lost.emit(reason)


func is_over() -> bool:
	return is_won or is_lost


## Build 012 round end (see header): immediate win, early impossible lose,
## then the old all-resolved fallback.
func _check_end() -> void:
	if not setup_complete or is_won or is_lost:
		return
	if total_humans < 1:
		return
	if rescued_humans >= target_rescued:
		trigger_win()
		return
	if max_possible_saves() < target_rescued:
		trigger_lose(
			"Target out of reach!  Saved %d/%d — needed %d" % [rescued_humans, total_humans, target_rescued],
			"impossible")
		return
	# Fallback (pre-012): everyone generated and resolved without reaching the target.
	if all_spawned() and resolved_humans() >= total_humans:
		trigger_lose("Saved %d/%d — needed %d" % [rescued_humans, total_humans, target_rescued], "short")
